version: '3.8'
services:
  postgres:
    image: postgres:13.2-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    network_mode: host

  app:
    container_name: ton
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    network_mode: host

  pgadmin:
    image: dpage/pgadmin4:5.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5433:80

volumes:
  postgres_volume:
  node_modules: {}
